version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "npm installing"
            - run: npm install
            - run: CI=true npm run build      
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "testing stuff"
            - run: npm install
            - run: npm test
  hithere:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "hellooo!"
workflows:
    build_test_and_lint:
      jobs:
        - build
        - hithere
        - test:
            requires:
              - hithere
