version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  bobby:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run:
                name: The First Step
                command: |
                  echo 'A first hello'
                  echo 'This is the delivery pipeline'
  sally:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run:
                name: The First Step
                command: |
                  echo 'Double trouble'
                  echo 'This is the delivery pipeline'          
workflows:
    bobby_sally:
      jobs:
        - bobby
        - sally
  
