export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_KITTENS_PENDING = "REQUEST_KITTENS_PENDING";
export const REQUEST_KITTENS_SUCCESS = "REQUEST_KITTENS_SUCCESS";
export const REQUEST_KITTENS_FAILED = "REQUEST_KITTENS_FAILED";
